### ISSUE TITLE
二者共存可能存在bug

### ISSUE THREAD

**Issue by CaoKang-David** [DustinWin/Router-Plugins#1]
你好，看了你这篇文章以后。我也在我家的asus merlin路由器上安装了clash和adgh，运行一阵子以后，就会内存泄露，导致路由器直接把clash进程kill了。
您这边有类似的情况吗？

**Comment by DustinWin** [comment]
内核是什么？优先用 Clash.Pre 内核，不兼容的话再用 Clash.Meta 内核。

**Comment by CaoKang-David** [comment]
三个内核都试过了，clash.pre干脆就不启不起来
后来，我发现很可能是因为这个问题：我一开始把梅林自带的dnsmasq禁用了，让adgh接管dns服务，但没有关闭路由上的dhcp服务，导致同时存在两个dhcp服务，引发了爆内存问题。后来我把系统dhcp服务关了，也由adgh接管就好了。到目前为止没有发现什么问题了。

**Comment by DustinWin** [comment]
> 
好的，我这边的设备是 Redmi AX6000，所以部分设置可能不一样。
